spring.application.name=cinemamax-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d85gt6rtqb8s7380nkq0-a:5432/cinema_db_2wl7
spring.datasource.username=cinemamax
spring.datasource.password=8UAgJc0oW8ifgcoSuLP4ZPN1zONap6IU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Run schema.sql on startup
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# Server port
server.port=${PORT:8080}

# CORS
cinemamax.cors.allowed-origins=${CORS_ORIGINS:https://byte4breach.github.io,https://web.telegram.org}